### ISSUE TITLE
GMRT_1gc_2gc with plots

### ISSUE THREAD

**Issue by sensingcosmos** [radiosky-abhik/stimela_123gc#1]
Hello Guys,
                    I am more or less satisfied with the current 1gc script. It includes several plots. Please check once if you want to add more. The more useful plots the script produces I think it is more better. 

                  I would like to run this 1gc script on the 325 MHz GMRT data and try to see different diagnostic plots that it produces. 

                 Currently, though it stops at the first plot cab "plot_phasecal_amp_R" and gives me the following error:

Error: No such container: plot_phasecal_amp_R-140402552858640149226478985
Task was not started.

               It seems something related with plotms. @SpheMakh can you please try to include plotms in stimela. Thanks.

Cheers,
 Abhik

**Comment by sensingcosmos** [comment]
I am running the 1gc & 2gc scripts in aretha at /net/ike/home/abhik/GMRT325_123GC_v3

**Comment by sensingcosmos** [comment]
It seems that the current 2gc script is giving a reasonable image before and after source subtraction. @SpheMakh : It will be nice if you can now sort out the 1gc and 2gc plotting issues, so that we can see the diagnostic plots as we move forward. Updated scripts are in the repository.
![2gc](https://cloud.githubusercontent.com/assets/25012975/25073102/43598426-22df-11e7-9004-786b38eee82a.png)
![2gc_res](https://cloud.githubusercontent.com/assets/25012975/25073103/438bca08-22df-11e7-996c-c4dd91f3daae.png)

**Comment by sphemakh** [comment]
This is great progress! 

What issues are you having with plotms?

**Comment by sensingcosmos** [comment]
Thanks Sphe. I hope plotms in stimela can take cal table in input?

In "plot_phasecal_amp_R" cab it gives me this error:

Error: No such container: plot_phasecal_amp_R-140402552858640149226478985
Task was not started.Error: No such container: plot_phasecal_amp_R-
140250127517712149237110671
Task was not started.

I have the cab like this:

recipe.add('cab/casa_plotms', 'plot_phasecal_amp_R',
           {
               "vis"  :   PHASECAL_TABLE,
               "correlation" :   'R',
               "xaxis"     :   'time',
               "yaxis"     :   'GainAmp',
               "field"     :   phase_cal,
               "figfile"   :   PREFIX+'amp-time-R.png',
           },
    input=INPUT,
    output=OUTPUT,
    label='plot_phasecal_amp_R:: Plot gaincal table. AMP, R')


I am running at /net/ike/home/abhik/GMRT325_1GC/

--  Abhik

<abhik@phy.iitkgp.ernet.in>
